import Head from "next/head";
import react from "react";
import NavigationBar from "/components/NavigationBar";
import Footer from "/components/Footer";
import "../styles/globals.css";
import styles from "../styles/Home.module.css";
import Image from "next/image";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>StarBound</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavigationBar />
      <Component {...pageProps} />
      <Footer />
    </>
  );
}

export default MyApp;
