import Head from "next/head";

import NavigationBar from "/components/NavigationBar";
// import ChatWidget from "../../components/ChatWidget";
import Footer from "/components/Footer";
import "../styles/globals.css";
import styles from "../styles/Home.module.css";
import Image from "next/image";

import "../styles/globals.css";
import { SessionProvider } from "next-auth/react";
function MyApp({ Component, pageProps, session }) {
  return (
    <>
      <SessionProvider>
        <Head>
          <title>StarBound</title>

          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <NavigationBar />

        <Component {...pageProps} />
        {/* <ChatWidget /> */}
        <Footer />
      </SessionProvider>
    </>
  );
}
export default MyApp;
