import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Starbound</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div>
          <h1> All Users</h1>
          <div class="card">
            <h4>UserName:{"John Doe"}</h4>
            <p>User Phone: {"123456786"}</p>
          </div>
          <div className="card">
            <h4>UserName:{"Jane Doe"}</h4>
            <p>User Phone: {"123456786"}</p>
          </div>
          <div class="card">
            <h4>UserName:{"Joe camaro"}</h4>
            <p>User Phone: {"123456786"}</p>
          </div>
        </div>
        <div className="destinations">
          
          <Link href='/destinations'><h1>Destinations</h1></Link>
          
        </div>
        <div className="depating-soon">
          <h4> Flights departing soon</h4>
          <div class="flight-card-left">
            <h5> Mars</h5>
            <p>Flight time: 14:20pm</p>
            <p>Flight Date: 04-07-2023</p>
            <p>Flight Origon: space-X, california</p>
          </div>
          <div class="flight-card-right">
            <h5> Neptune</h5>
            <p>Flight time: 14:20pm</p>
            <p>Flight Date: 04-07-2023</p>
            <p>Flight Origon: space-X, california</p>
          </div>
          <button>
            <Link href="/bookings"> Book your Trip</Link>
          </button>
        </div>
      </main>
    </>
  );
}