import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

import Link from "next/link";
import { useEffect, useState } from "react";
const inter = Inter({ subsets: ["latin"] });

// destructure session and supabase out of the props being passed into the function
export default function Home({ session, supabase }) {
  const [loggedIn, setLoggedIn] = useState(false);
  useEffect(() => {
    // !! will turn session into a boolean and check to see if it has any data inside it
    setLoggedIn(!!session);
    // look for variables inside the function that could change
  }, [session]);
  return (
    <>
      <Head>
        <title>Starbound</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* If loggedIn is true, return text that says user is logged in, else return a log in button */}
        {loggedIn ? (
          <span>Welcome, ${user}</span>
        ) : (
          <button label="Login"></button>
        )}
        <div className={styles.users}>
          <h1> All Users</h1>
          <div class="card">
            <h4>UserName:{"John Doe"}</h4>
            <p>User Phone: {"123456786"}</p>
          </div>
          <div className="card">
            <h4>UserName:{"Jane Doe"}</h4>
            <p>User Phone: {"123456786"}</p>
          </div>
          <div class="card">
            <h4>UserName:{"Joe camaro"}</h4>
            <p>User Phone: {"123456786"}</p>
          </div>
        </div>
        <div className={styles.destination}>
          <h1> Destinations</h1>
          <div class="destination-card">
            <img src={".."} className="product-img" />
            <h4>
              <Link href="/jupitor">{"Jupitor"}</Link>
            </h4>
            <p>info about destination</p>
          </div>
          <div class="destination-card">
            <img src={".."} className="product-img" />
            <h4>
              <Link href="/mars">{"Mars"}</Link>
            </h4>
            <p>info about destination</p>
          </div>
          <div class="destination-card">
            <img src={".."} className="product-img" />
            <h4>
              <Link href="/neptune">{"Neptune"}</Link>
            </h4>
            <p>info about destination</p>
          </div>
        </div>
        <div className={styles.departingSoon}>
          <h4> Flights departing soon</h4>
          <div class="flight-card-left">
            <h5> Mars</h5>
            <p>Flight time: 14:20pm</p>
            <p>Flight Date: 04-07-2023</p>
            <p>Flight Origon: space-X, california</p>
          </div>
          <div class="flight-card-right">
            <h5> Neptune</h5>
            <p>Flight time: 14:20pm</p>
            <p>Flight Date: 04-07-2023</p>
            <p>Flight Origon: space-X, california</p>
          </div>
          <button>
            <Link href="/bookings"> Book your Trip</Link>
          </button>
        </div>
      </main>
    </>
  );
}
